-- Subscriptions кестесінің құрылымын тексеру
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Subscriptions'
ORDER BY ORDINAL_POSITION;

-- Егер бағандар жоқ болса, қайта қосу
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Subscriptions' AND COLUMN_NAME = 'CreatedAt')
BEGIN
    ALTER TABLE Subscriptions ADD CreatedAt datetime2 NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Subscriptions' AND COLUMN_NAME = 'Price')
BEGIN
    ALTER TABLE Subscriptions ADD Price decimal(18,2) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Subscriptions' AND COLUMN_NAME = 'Type')
BEGIN
    ALTER TABLE Subscriptions ADD [Type] nvarchar(50) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Subscriptions' AND COLUMN_NAME = 'DurationInDays')
BEGIN
    ALTER TABLE Subscriptions ADD DurationInDays int NULL;
END

-- Қайта тексеру
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Subscriptions'
ORDER BY ORDINAL_POSITION;
